spring:
  datasource:
    url: ${databaseUrl}
    username: ${usernameDB}
    password: ${passwordDB}
    hikari:
      connection-test-query: SELECT 1

  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate

  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true

server:
  port: ${PORT:8080}